export { K916, KeyboardBusyError, WritesDisabledError, type Backup, type ConnectOptions, type DeviceInfo, type RestoreStep } from './device.js'
export { buildFrame, checksum, FRAME_BODY_BYTES, FRAME_BYTES, type Bytes } from './frame.js'
export { bytesOf, parseCapture, toHex, type CaptureDirection, type CaptureEvent, type Transport } from './transport/transport.js'
export { MockTransport } from './transport/mock.js'
export { WebHIDTransport } from './transport/webhid.js'
export { Command, missingIndices, reassemble, WriteCommand, type Dialect, type ReplyPacket, type RequestArgs } from './dialect/dialect.js'
export { connectionTypeFor, dialectFor, VENDOR_ID_DONGLE, VENDOR_ID_WIRED, type ConnectionType } from './dialect/select.js'
export { WirelessDialect } from './dialect/wireless.js'
export { WiredDialect } from './dialect/wired.js'
export { decodeIdentity, type Identity } from './codec/identity.js'
export { decodePower, isPowerPacket, POWER_OPCODE, type PowerState } from './codec/power.js'
export { applySleep, decodeSleep, SLEEP_MINUTES_MAX, SLEEP_MINUTES_MIN, type SleepTimer } from './codec/sleep.js'
export { BYTES_PER_SLOT, decodeKeymap, Layer, SlotType, type KeyBinding } from './codec/keymap.js'
export { applyLighting, decodeLighting, EFFECTS, effectById, PROFILE_BYTES, type ColourMode, type Effect, type LightingChange, type LightingLimits, type LightingState } from './codec/lighting.js'
export { CUSTOM_COLOUR_BYTES, CUSTOM_SLOTS, decodeKeyColours, effectColour, fromHexColour, keyColour, LIGHT_COLOUR_READ_BYTES, LIGHT_COLOUR_WRITE_BYTES, lightColourWriteBlock, toHexColour, withEffectColour, withKeyColour, type RGB } from './codec/colour.js'
export { K1_PRO_UUID, modelForUuid, type Capabilities, type LightingRange, type Model } from './models.js'
export { codeToKey, isKnownCode, KEYCODES, keyToCode } from './keycodes.js'

export const VERSION = '0.1.0'
